[workspace]
resolver = "2"
members = [ "crates/hermione-memories", "crates/hermione-eyes"]

[workspace.dependencies]
anyhow = "1.0.89"
dirs = "5.0.1"
eyre = "0.6.12"
ratatui = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.63"

hermione-memories = { path = "crates/hermione-memories" }
