[workspace]
resolver = "2"
members = [
    "crates/hermione-coordinator",
    "crates/hermione-core",
    "crates/hermione-json",
    "crates/hermione-notion-serde",
    "crates/hermione-notion",
    "crates/hermione-powershell",
    "crates/hermione-terminal",
]

[workspace.dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
dirs = "5.0.1"
eyre = "0.6.12"
ratatui = "0.28.1"
reqwest = "0.12.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.63"
tokio = "1.40.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = "1.10.0"

hermione-coordinator = { path = "crates/hermione-coordinator" }
hermione-core = { path = "crates/hermione-core" }
hermione-json = { path = "crates/hermione-json" }
hermione-notion = { path = "crates/hermione-notion" }
hermione-notion-serde = { path = "crates/hermione-notion-serde" }
hermione-powershell = { path = "crates/hermione-powershell" }
