[workspace]
resolver = "2"
members = [
    "crates/hermione-memories",
    "crates/hermione-eyes",
    "crates/hermione-deeds",
    "crates/hermione-wand",
    "crates/hermione-json",
]

[workspace.dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
dirs = "5.0.1"
eyre = "0.6.12"
ratatui = "0.28.1"
reqwest = "0.12.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.63"
tokio = "1.40.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = "1.10.0"

hermione-memories = { path = "crates/hermione-memories" }
hermione-deeds = { path = "crates/hermione-deeds" }
hermione-wand = { path = "crates/hermione-wand" }
hermione-json = { path = "crates/hermione-json" }
