[package]
name = "hermione-ops"
version = "0.1.0"
edition = "2021"

[lib]
name = "hermione_ops"

[dependencies]
chrono = {workspace = true}
eyre = {workspace = true}
thiserror = {workspace = true}
uuid = { workspace = true }
