[package]
name = "hermione-terminal-directory"
version = "0.1.0"
edition = "2021"

[lib]
name = "hermione_terminal_directory"

[dependencies]
anyhow = { workspace = true }
dirs = { workspace = true }
