[package]
name = "hermione-tracing"
version = "0.1.0"
edition = "2021"

[lib]
name = "hermione_tracing"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
