[package]
name = "hermione-logs"
version = "0.1.0"
edition = "2021"

[lib]
name = "hermione_logs"

[dependencies]
anyhow = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
