[package]
name = "hermione-terminal"
version = "0.1.0"
edition = "2021"
default-run = "hermione-terminal"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
eyre = { workspace = true }
ratatui = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }

hermione-coordinator = { workspace = true }
hermione-tracing = { workspace = true }
hermione-powershell = { workspace = true }
hermione-terminal-directory = { workspace = true }
hermione-tui = { workspace = true }
