[package]
name = "hermione-terminal"
version = "0.1.0"
edition = "2021"
default-run = "hermione-terminal"

[dependencies]
anyhow = { workspace = true }
eyre = { workspace = true }
ratatui = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }

hermione-coordinator = { workspace = true }
hermione-storage = { workspace = true }
hermione-tracing = { workspace = true }
hermione-tui = { workspace = true }
