[package]
name = "hermione-memories"
version = "0.1.0"
edition = "2021"

[lib]
name = "hermione_memories"

[dependencies]
chrono = {workspace = true}
eyre = {workspace = true}
thiserror = {workspace = true}
uuid = { workspace = true, features = ["v4"] }
