[package]
name = "hermione-wand"
version = "0.1.0"
edition = "2021"

[lib]
name = "hermione_wand"

[dependencies]
eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
