[package]
name = "hermione-powershell"
version = "0.1.0"
edition = "2021"

[lib]
name = "hermione_powershell"

[dependencies]
anyhow = { workspace = true }
eyre = { workspace = true }
thiserror = { workspace = true }
