[package]
name = "hermione-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { workspace = true }
anyhow = { workspace = true }
eyre = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

hermione-memory = { workspace = true }
